AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MatillionAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionUri: matillion-swagger.json

Outputs:

    MatillionAPI:
      Description: "Root API endpoint URL for test stage"
      #Value: !Sub "https://${MatillionAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"
      Value: !Sub "http://ec2-34-253-225-241.eu-west-1.compute.amazonaws.com/rest/v1"
      Export:
        Name: MatillionAPIRoot