version: 0.2
phases:
  install:
    commands:
      - cd 01api
      - aws cloudformation package --template-file matillion-api.yaml
                                   --s3-bucket aws-codepipeline-codebuild-with-postman-ssegerma
                                   --s3-prefix api-code
                                   --output-template-file matillion-api-output.yaml
artifacts:
  type: zip
  files:
    - 01api/matillion-api-output.yaml
